cmake_minimum_required(VERSION 3.21)
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
file(REAL_PATH "${TEST_ROOT}" real_root)
set(root "${real_root}/adapter-cli-${suffix}")
file(MAKE_DIRECTORY "${root}/store")
file(WRITE "${root}/context" "abc")
execute_process(COMMAND "${CLI}" adapter noop probe RESULT_VARIABLE status OUTPUT_VARIABLE probe)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Capability probe failed")
endif()
string(JSON simulation GET "${probe}" simulation)
string(JSON adapter GET "${probe}" adapter_id)
if(NOT simulation STREQUAL "1" OR NOT adapter STREQUAL "local.noop")
    message(FATAL_ERROR "Invalid noop capabilities")
endif()
execute_process(COMMAND "${CLI}" evidence put "${root}/store" "${root}/context"
    RESULT_VARIABLE status OUTPUT_VARIABLE receipt)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Context publication failed")
endif()
string(JSON digest GET "${receipt}" digest)
set(zero "0000000000000000000000000000000000000000000000000000000000000000")
set(request "{\"type\":\"2\",\"version\":\"1\",\"request_id\":\"cli-1\",\"run_id\":\"cli-run\",\"adapter_id\":\"local.noop\",\"stage\":\"0\",\"sequence\":\"1\",\"attempt\":\"1\",\"context_version\":\"1\",\"context_algorithm\":\"1\",\"context_size\":\"3\",\"context_digest\":\"${digest}\",\"has_predecessor\":\"0\",\"predecessor_digest\":\"${zero}\"}")
file(WRITE "${root}/request.json" "${request}")
execute_process(COMMAND "${CLI}" adapter noop run "${root}/store" INPUT_FILE "${root}/request.json"
    RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE error)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Noop run failed: ${error}")
endif()
foreach(pair "type;3" "simulation;1" "outcome;2" "cost_known;1" "nano_cost;0" "request_id;cli-1")
    list(GET pair 0 key)
    list(GET pair 1 expected)
    string(JSON actual GET "${result}" "${key}")
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Unexpected ${key}: ${actual}")
    endif()
endforeach()
string(JSON evidence GET "${result}" evidence_digest)
execute_process(COMMAND "${CLI}" adapter convert json msgpack INPUT_FILE "${root}/request.json"
    OUTPUT_FILE "${root}/request.msgpack" RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "JSON to MessagePack conversion failed")
endif()
execute_process(COMMAND "${CLI}" adapter noop run "${root}/store" --format msgpack INPUT_FILE "${root}/request.msgpack"
    OUTPUT_FILE "${root}/result.msgpack" RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "MessagePack noop failed")
endif()
execute_process(COMMAND "${CLI}" adapter convert msgpack json INPUT_FILE "${root}/result.msgpack"
    OUTPUT_VARIABLE converted RESULT_VARIABLE status)
if(NOT status EQUAL 0 OR NOT converted STREQUAL result)
    message(FATAL_ERROR "Cross-codec result/evidence mismatch")
endif()
execute_process(COMMAND "${CLI}" adapter noop probe --format msgpack
    OUTPUT_FILE "${root}/probe.msgpack" RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "MessagePack capability probe failed")
endif()
execute_process(COMMAND "${CLI}" adapter convert msgpack json INPUT_FILE "${root}/probe.msgpack"
    OUTPUT_VARIABLE converted RESULT_VARIABLE status)
if(NOT status EQUAL 0 OR NOT converted STREQUAL probe)
    message(FATAL_ERROR "Cross-codec capability mismatch")
endif()
execute_process(COMMAND "${CLI}" adapter convert msgpack json INPUT_FILE "${root}/request.json"
    OUTPUT_VARIABLE output ERROR_QUIET RESULT_VARIABLE status)
if(NOT status EQUAL 1 OR NOT output STREQUAL "")
    message(FATAL_ERROR "Format mismatch accepted")
endif()
execute_process(COMMAND "${CLI}" adapter noop probe --format unknown OUTPUT_VARIABLE output ERROR_QUIET RESULT_VARIABLE status)
if(NOT status EQUAL 2 OR NOT output STREQUAL "")
    message(FATAL_ERROR "Unknown encoding accepted")
endif()
execute_process(COMMAND "${CLI}" evidence verify "${root}/store" "${evidence}" RESULT_VARIABLE status OUTPUT_QUIET)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Result evidence did not verify")
endif()
foreach(bad "{}" "${request}${request}" "${probe}")
    file(WRITE "${root}/request.json" "${bad}")
    execute_process(COMMAND "${CLI}" adapter noop run "${root}/store" INPUT_FILE "${root}/request.json"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_QUIET)
    if(NOT status EQUAL 1 OR NOT output STREQUAL "")
        message(FATAL_ERROR "Invalid input emitted success")
    endif()
endforeach()
string(REPEAT "x" 16385 oversized)
file(WRITE "${root}/request.json" "${oversized}")
execute_process(COMMAND "${CLI}" adapter noop run "${root}/store" INPUT_FILE "${root}/request.json"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_QUIET)
if(NOT status EQUAL 1 OR NOT output STREQUAL "")
    message(FATAL_ERROR "Oversized input accepted")
endif()
string(SUBSTRING "${digest}" 0 2 shard)
string(SUBSTRING "${digest}" 2 62 leaf)
set(object "${root}/store/objects/sha256/${shard}/${leaf}")
file(CHMOD "${object}" PERMISSIONS OWNER_READ OWNER_WRITE)
file(WRITE "${object}" "abd")
file(WRITE "${root}/request.json" "${request}")
execute_process(COMMAND "${CLI}" adapter noop run "${root}/store" INPUT_FILE "${root}/request.json"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 1 OR NOT output STREQUAL "" OR NOT error MATCHES "digest mismatch")
    message(FATAL_ERROR "Corrupt context was not rejected")
endif()
file(REMOVE_RECURSE "${root}")
