cmake_minimum_required(VERSION 3.21)
# Each invocation owns a fresh directory; no shared mutable fixture or test order.
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
file(REAL_PATH "${TEST_ROOT}" real_root)
set(root "${real_root}/evidence-cli-${suffix}")
file(MAKE_DIRECTORY "${root}/store")
file(WRITE "${root}/artifact" "abc")
set(digest "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")

function(run expected)
    execute_process(COMMAND "${CLI}" ${ARGN} RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
    if(NOT "${result}" STREQUAL "${expected}")
        message(FATAL_ERROR "${ARGN}: expected ${expected}, got ${result}: ${error}")
    endif()
    if(NOT expected EQUAL 0 AND NOT output STREQUAL "")
        message(FATAL_ERROR "Failure emitted a success projection: ${output}")
    endif()
    set(json "${output}" PARENT_SCOPE)
    set(error "${error}" PARENT_SCOPE)
endfunction()

run(0 evidence hash "${root}/artifact")
string(JSON actual GET "${json}" digest)
if(NOT actual STREQUAL digest)
    message(FATAL_ERROR "Wrong artifact digest")
endif()
run(0 evidence put "${root}/store" "${root}/artifact")
string(JSON actual GET "${json}" digest)
string(JSON size GET "${json}" size)
string(JSON receipt GET "${json}" receipt_digest)
if(NOT actual STREQUAL digest OR NOT size EQUAL 3)
    message(FATAL_ERROR "Wrong put projection")
endif()
run(0 evidence verify "${root}/store" "${digest}")
string(JSON verified GET "${json}" verified)
if(NOT verified)
    message(FATAL_ERROR "Missing verification flag")
endif()
run(0 evidence verify-receipt "${root}/store" "${receipt}")
run(1 evidence verify "${root}/missing" "${digest}")
if(EXISTS "${root}/missing")
    message(FATAL_ERROR "Verify created a missing store")
endif()
run(1 evidence verify "${root}/store" "../../arbitrary")
run(2 evidence verify "${root}/store")
run(2 evidence unknown)
set(object "${root}/store/objects/sha256/ba/7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
file(CHMOD "${object}" PERMISSIONS OWNER_READ OWNER_WRITE)
file(WRITE "${object}" "abd")
run(1 evidence verify "${root}/store" "${digest}")
if(NOT error MATCHES "digest mismatch")
    message(FATAL_ERROR "Missing digest mismatch diagnostic: ${error}")
endif()
run(1 evidence verify-receipt "${root}/store" "${receipt}")
run(1 evidence put "${root}/store" "${root}/artifact")
file(READ "${object}" unchanged)
if(NOT unchanged STREQUAL "abd")
    message(FATAL_ERROR "Put overwrote a corrupt existing object")
endif()
file(REMOVE_RECURSE "${root}")
