cmake_minimum_required(VERSION 3.21)
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
file(REAL_PATH "${TEST_ROOT}" real_root)
set(root "${real_root}/lineage-cli-${suffix}")
file(MAKE_DIRECTORY "${root}")
execute_process(COMMAND "${FIXTURE}" fixture "${root}" RESULT_VARIABLE result OUTPUT_VARIABLE key ERROR_VARIABLE error TIMEOUT 20)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot create fixture: ${error}")
endif()
string(STRIP "${key}" key)
function(run expected)
    execute_process(COMMAND "${CLI}" ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE json ERROR_VARIABLE error TIMEOUT 20)
    if(NOT "${result}" STREQUAL "${expected}")
        message(FATAL_ERROR "${ARGN}: expected ${expected}, got ${result}: ${error}")
    endif()
    if(NOT expected EQUAL 0 AND NOT json STREQUAL "")
        message(FATAL_ERROR "Error emitted success JSON")
    endif()
    set(json "${json}" PARENT_SCOPE)
endfunction()
run(0 lineage verify "${root}" "${key}")
string(JSON count GET "${json}" stages)
if(NOT count EQUAL 3)
    message(FATAL_ERROR "Wrong stage count")
endif()
run(0 lineage trace "${root}" "${key}" 3)
string(JSON count LENGTH "${json}" predecessors)
string(JSON sequence GET "${json}" predecessors 0 sequence)
if(NOT count EQUAL 2 OR NOT sequence EQUAL 1)
    message(FATAL_ERROR "Incomplete transitive trace")
endif()
run(0 lineage trace "${root}" "${key}" 3 --direct)
string(JSON count LENGTH "${json}" predecessors)
string(JSON sequence GET "${json}" predecessors 0 sequence)
if(NOT count EQUAL 1 OR NOT sequence EQUAL 2)
    message(FATAL_ERROR "Wrong direct trace")
endif()
run(0 lineage trace "${root}" "${key}" 1)
string(JSON count LENGTH "${json}" predecessors)
if(NOT count EQUAL 0)
    message(FATAL_ERROR "First stage has predecessors")
endif()
run(1 lineage trace "${root}" "${key}" 4)
run(2 lineage trace "${root}" "${key}" -1)
run(2 lineage trace "${root}" "${key}" 18446744073709551616)
run(2 lineage trace "${root}" "${key}" 2 --unknown)
run(1 lineage verify "${root}" bad-digest)
run(1 lineage verify "${root}/missing" "${key}")
if(EXISTS "${root}/missing")
    message(FATAL_ERROR "Read-only CLI created store")
endif()
set(object "${root}/objects/sha256/ba/7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
file(CHMOD "${object}" PERMISSIONS OWNER_READ OWNER_WRITE)
file(WRITE "${object}" "abd")
run(1 lineage verify "${root}" "${key}")
run(1 lineage trace "${root}" "${key}" 3)
file(REMOVE_RECURSE "${root}")
